# Generated by Django 5.2 on 2025-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField()),
                ('label', models.CharField(blank=True, choices=[('positif', 'Positif'), ('negatif', 'Negatif')], max_length=10)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
