# Generated by Django 5.2 on 2025-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analisis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ulasan",
            name="nama",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ulasan",
            name="rating",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ulasan",
            name="review_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ulasan",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("google", "Google")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
